### PR TITLE
Session page for 2024-11-22: Single Process Micro-service Architecture

### PR DESCRIPTION
**Pull request by dawedawe**

### CODE REVIEW

**Review by nojaf — APPROVED** [review]

**Comment by juselius** [comment]
I'm getting in contact with @swlaschin and we'll come up with an agenda soon.

**Comment by dawedawe** [comment]
> I'm getting in contact with @swlaschin and we'll come up with an agenda soon.

Super nice, thanks!

**Comment by dawedawe** [comment]
Maybe I misunderstood your message. I thought you wanted to include an agenda in the announcement. But as it's not critical at all, I'll just publish.

**Comment by juselius** [comment]
Ah yes! I’ll coordinate with Scott and post something early tomorrow.

**Comment by juselius** [comment]
Sorry for being slow... Here is a suggestion:

Micro-service architecture is a popular design pattern among serious cloud architects. There are good reasons for using Domain-Driven Design  together with the strict boundaries provided by disparate services. Unfortunately there is a price to pay: The complexity of deploying and operating multiple distinct, distributed services quickly becomes high.

In this presentation we examine the virtues of micro-services, while retaining the operational simplicity of the monolith. We present a flexible scheme based on Dapr Actors in F#, allowing us to get the best of both worlds: Strict domain boundaries, running inside a single monolith. We also show how the monolith almost trivially and transparently can be split, if hard realities dictate the need. Behold, the Single-Process Micro Service Architecture(tm)!

Your thoughts @swlaschin?

**Comment by swlaschin** [comment]
Looks good to me!

**Comment by dawedawe** [comment]
Thanks a lot. The session page is updated.

**Pull request merged**
