### PR TITLE
Session 2023-11-10

### PR DESCRIPTION
**Pull request by TheAngryByrd**

### CODE REVIEW

**Review by edgarfgp — APPROVED** [review]

**Comment by RonaldSchlenker** [comment]
Apart from the word "lackluster", which I personally (as a non-native speaker) don't understand straight away, I think the session is ok.

In my opinion, our sessions have a strong focus on implementation and therefore less on the reasons why things are there in the first place and for what purpose they are useful in which scenarios. Example: "Analyzer". This was a very interesting session on the topic of "How do they work / how can you write them / how do you call them". So: focus on "how", but not on "why", e.g: When does it make sense to use them / placing them in an overall context / use cases / etc.?

If you are of the opinion that the "why" should be given a little more focus (I always find this very exciting, but there are certainly different views on this), I have brainstormed a few points here ("raw brainstorming"), which are to be understood as suggestions:

- What are the benefits of having signature files?
- Why are they so controversal?
- When and how should a project introduce them?
- Why other languages don't have signature files and - would you miss them?
- Signature files - for technical or other purpose? (think of C header files; same purpose - different purpose)?
- Real drawbacks not having them in a project - could you live without them?
- Is the presence of sig files related to non-mainstream features like type inference?
- etc...

**Review by dawedawe — APPROVED** [review]

**Comment by nojaf** [comment]
Not really related to the description, but out of curiosity I'd like to know what your concrete ideas are.

**Comment by nojaf** [comment]
@RonaldSchlenker not a 100% what you are after but some pointers can be found in https://nojaf.com/telplin/docs/motivation.html

**Review by RonaldSchlenker — APPROVED** [review]

**Comment by RonaldSchlenker** [comment]
> Not really related to the description

Yes, with the points I mentioned, the session would get a different touch.

> ...what your concrete ideas are.

I mean, it's nice to talk about "Better support for signature files in FsAutocomplete". That can be the session - it would be ok for me. In addition, it might be interesting to have an open or a guided discussion on the topic "signature files" itself - with the points I outlined above.

From my personal point of view, I as part of the audience, could ask myself: "Nice having better support for that - but I don't use them. Should I use them?" or "If I use them, what's a good starting point, how much work would it be to incorporating them in my existing project / is it a pain having them and having the need for changing an existing API / What benefits do I get from having them / etc.".

In the Telpin session, there was a short duration where we had these discussions, and I found that very valuable.

To get to a session-format that could work, here a proposal:

The session could have a discussion part, followed by the "Better support for signature files in FsAutocomplete". In the discussion part, the care taker could moderate through a known set of topics or questions that the audience (or we) could comment on. Or it could be vice versa.

It's an idea - I'm not even sure if we should do it, but it might give the session a little kick in terms of background knowledge and interactivity.

**Comment by edgarfgp** [comment]
@TheAngryByrd Happy to merge this so we can announce it :)  ?

**Pull request merged**
