### PR TITLE
Fsharp components

### PR DESCRIPTION
**Pull request by nojaf**
Code from https://amplifyingfsharp.io/sessions/2024/04/12/
Needs some more work.

### CODE REVIEW

**Comment by nojaf** [comment]
I think this is done.
You might want to try this on your local machine when reviewing.

**Review by dawedawe — APPROVED** [review]
One thing I noticed is that the dev server (only tried on Linux) shows a partially loaded page: 
image
After a refresh, everything is there.

**Comment by nojaf** [comment]
> One thing I noticed is that the dev server (only tried on Linux) shows a partially loaded page:

Yes, I have that one as well. This would be a Bun problem. I don't have this with Node. 😊😅😇

**Comment by dawedawe** [comment]
> Yes, I have that one as well. This would be a Bun problem. I don't have this with Node. 😊😅😇

8nf5vl

**Pull request merged**
