### PR TITLE
Add embedded youtube video links to completed sessions.

### PR DESCRIPTION
**Pull request by TheAngryByrd**
- [Adds embedded youtube links to completed sessions](https://github.com/amplifying-fsharp/amplifying-fsharp.github.io/commit/49b8afecdac1a4c0033ac011de04a99df435d55e)
image

- [Renamed sessions to YYYY-MM-DD](https://github.com/amplifying-fsharp/amplifying-fsharp.github.io/commit/e9cfb791f1b4b985ddd567586557db34823b9786) as this could get unwieldy if we have more sessions beyond this month.

### CODE REVIEW

**Comment by TheAngryByrd** [comment]
image

Locally I'm getting the day's off by one. Should I edit `session.astro` to add one?

**Comment by edgarfgp** [comment]
I was wondering the same . Will investigate a bit

**Comment by nojaf** [comment]
> Locally I'm getting the day's off by one. Should I edit session.astro to add one?

Yup, I just fixed that in 783aa7528316ef21742a667e2087e125e22df736

**Comment by edgarfgp** [comment]
merged your changes to main and updated a new session recently added :). Thanks for the PR

**Pull request closed without merging**
